### ISSUE TITLE
change brightness of rainbow with LED key

### ISSUE THREAD

**Issue by qayshp** [keyboardio/Kaleidoscope-LEDEffect-Rainbow#8]
Sorry if I'm missing something, but I don't currently see a way to change LED brightness of Rainbow mode without recompiling and flashing. It would be awesome to be able to toggle between settings with the LED key (or some other way) to change brightness throughout the day.

**Comment by algernon** [comment]
You can do that with a macro:

```c++
static rainbow_brightness = 50;

void macroRainbowBrightInc(uint8_t keyState) {
  if (!keyToggledOn(keyState)) {
    rainbow_brightness += 10;
    LEDRainbowEffect.brightness(rainbow_brightness);
    LEDRainbowWaveEffect.brightness(rainbow_brightness);
  }
};
```

Would be easier if we had a way to query the current brightness... I'll add that in a bit, and then the code will look like this:

```c++
void macroRainbowBrightInc(uint8_t keyState) {
  if (!keyToggledOn(keyState)) {
    LEDRainbowEffect.brightness(LEDRainbowEffect.brightness() + 10);
    LEDRainbowWaveEffect.brightness(LEDRainbowWaveEffect.brightness() + 10);
  }
};
```

...and similarly for the other way. Bind these two to a key or two on the Fn layer for example, and you have a key to adjust rainbow brightness at run time!

**Comment by qayshp** [comment]
Will try that out when I'm back at my desk! Thanks!

**Comment by algernon** [comment]
Pushed the getters, so you can try the second, cleaner version :)

**Comment by algernon** [comment]
As this should not be possible, I'm closing the issue. Feel free to reopen if setting brightness is still not solved!
